### ISSUE TITLE
Session dependency of Event Manager [session]

### ISSUE THREAD

**Issue by Surt** [zendframework/zf2#5268] opened 2013-10-14 19:57 UTC
Hi, I was triying to use the Zend_Session as a component, standalone package, but if I require it alone on my composer I fail to make it work, as a fatal Error occurs `Fatal error: Class 'Zend\EventManager\EventManager'`  or, if I require it, the `Zend\ServiceManager\AbstractPluginManager` Fatal Error appears.

Is it possible to get rid of this dependencies?

**Comment by adamlundrigan** [comment] 2015-10-21 16:59
@Maks3w this can be closed.  Is a duplicate of #6818 (fixed)

**Closed** 2015-10-21 17:02 UTC
Labels: EventManager, Session
