### ISSUE TITLE
Zend\Form\Form::getInputFilter() issue with Collection Element

### ISSUE THREAD

**Issue by YannickDa** [zendframework/zf2#4703] opened 2013-06-21 15:31 UTC
Hi !

I'm working on a project and I think that the method getInputFilter() of the class Zend\Form\Form must be rewrited.

If we have an Element of type Collection where we can add some new values and we want to get the input filter before to set any data from POST to the form, we have an issue because when we populate values with data POST after that we have getting the input filter of form, the validators, filters & co was not initialized with the new values of the collection... So, we can't validate theses new values and can't get filtered values.

I have not any time for now to propose a correction about that but if you can give me some reflexions about that, you are welcome :)

**Comment by adamlundrigan** [comment] 2015-10-21 22:44
This looks to be a duplicate of #5243, which appears to be fixed.  You can pull the InputFilter instance before populating the form and the same instance will be updated accordingly when bind or setData is called on the form.  

Is this still an issue for you, @YannickDa ?

**Closed** 2015-11-05 04:37 UTC
Labels: Form
