### ISSUE TITLE
Multiple file validators with MimeType causes memory leak

### ISSUE THREAD

**Issue by Dawiss** [zendframework/zf2#7629] opened 2015-09-27 14:10 UTC
After tracing down memory leak in my ZF2 application I think using MimeType(code bellow) with multiple other validators causes memory leak. Removing MimeType validator solves it.

PHP: 5.6.4-4ubuntu6.2
Apache: 2.4.10 (Ubuntu)
ZF2: 2.5.2

Filter for form that is used for picture upload:
```php
namespace Admin\Filter;

use Zend\InputFilter\InputFilter;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

class PictureFilter implements InputFilterAwareInterface
{
    protected $inputFilter;

    public function __construct()
    {
        $inputFilter = new InputFilter();
        $this->inputFilter = $inputFilter;
    }

    public function getInputFilter()
    {
        $this->inputFilter->add(array(
            'name' => 'file',
            'required' => true,
            'validators' => array(
                array(
                    'name' => 'File\Size',
                    'options' => array(
                        'min' => '10kB',
                        'max' => '2MB',
                    ),
                ),
                array(
                    'name' => 'File\Extension',
                    'options' => array(
                        'extension' => array('png', 'jpg', 'gif')
                    )
                ),
                array(
                    'name' => 'File\MimeType',
                    'options' => array(
                        'mimeType' => array('image/png', 'image/jpeg', 'image/pjpeg', 'image/gif')
                    )
                ),
                array(
                    'name' => 'File\UploadFile',
                ),
            ),
        ));

        return $this->inputFilter;
    }
}
```

Form that is used for picture upload:
```php
namespace Admin\Form;

use Zend\Form\Form;
use Zend\Form\Element;

class PictureForm extends Form
{
    public function __construct()
    {
        parent::__construct();

        $this->setAttribute('method', 'post');

        //Picture
        $this->add(array(
            'name' => 'file',
            'type' => 'File',
        ));
    }
}
```
Controller code that creates picture form and filter which are used to validate posted picture:
```php

                //Retrieve posted file
                $file = $request->getFiles()->toArray();

                //Get picture form and filter
                $pictureForm = new PictureForm();
                $pictureFilter = new PictureFilter();

                //Set filter and data to form
                $pictureForm->setInputFilter($pictureFilter->getInputFilter());
                $pictureForm->setData($file);


//                Check if file is a valid picture
                if ($pictureForm->isValid()) {
                    //Memory leak!
                }
```

Message from log files:
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 140651221885936 bytes) in Unknown on line 0, referer:
```

**Comment by macnibblet** [comment] 2015-10-10 19:18
Can you try without the magicFile enabled in the mimtype validator ?

**Comment by Maks3w** [comment] 2016-01-29 15:58
The shortest code for reproduce the warning:

PHP: PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
/usr/share/file/magic.mgc: magic binary file for file(1) cmd (version 10) (little endian)

```php
finfo_open(FILEINFO_MIME_TYPE, '/usr/share/file/magic.mgc');
```

**Comment by Maks3w** [comment] 2016-01-29 16:44
Workaround is disable magicFile with the following two options:

 `['disableMagicFile' => true, 'magicFile' => false]`

**Comment by Maks3w** [comment] 2016-01-29 19:54
I'll close this because is a PHP bug occurs while shutdown (destroy finfo object instance) https://bugs.php.net/bug.php?id=66885

**Closed by Maks3w** 2016-01-29 19:54 UTC
Labels: Validator

**Comment by philippe-jung** [comment] 2017-04-24 14:02
I had the same issue, and I think there might be a reasonable fix: calling finfo_close after reading the file.

in library/Zend/Validator/File/MimeType.php line 393,
add
finfo_close($this->finfo);

It seems to fix the problem.
I would be happy to create a proper merge request if you think that is an acceptable solution.

**Comment by weierophinney** [comment] 2017-04-24 14:09
@philippe-jung Please create a pull request, including a test demonstrating the issue and confirming the fix, against [zendframeworkz/zend-validator](https://github.com/zendframework/zend-validator).
