### ISSUE TITLE
Zend\Session always invoked, cookie overload

### ISSUE THREAD

**Issue by al3xdm** [zendframework/zf2#6733] opened 2014-10-04 13:58 UTC
We're using DynamoDB as our session storage and I had to start debugging an issue. We were using a lot of read/write capacity even though we had relatively few logged in users.

The issue is that Zend\Session seems to be really eager in creating new sessions instead of lazy loaded. Our Modules make use of Session Containers for things like Login, Baskets, Order states etc. However, using Containers seems to start the Session Manager automatically ( https://github.com/zendframework/zf2/blob/master/library/Zend/Session/AbstractContainer.php#L78 ) whether it's needed or not.

To put an idea on the size of problem... we're writing 500,000 empty rows to DynamoDB every 12 hours from bots and logged our users on the site browsing. They're having Sessions created (and cookies set) unnecessarily, there shouldn't be any.

Is there a way to get Zend\Session and/or Containers to work in a lazy manner? Only loading if there's session data? Seems like this should be the default behaviour as having cookies set also massively interferes with our ability to cache.

**Comment by adamlundrigan** [comment] 2015-11-06 19:36
Duplicate of #4332

**Closed by adamlundrigan** 2015-11-06 19:36 UTC
