### ISSUE TITLE
Composer update no-dev loads dependencies from require-dev

### ISSUE THREAD

**Issue by googlle** [zendframework/zf2#7588] opened 2015-06-16 10:34 UTC
Composer loads dependencies from require-dev:
doctrine/instantiator
phpdocumentor/reflection-docblock
phpspec/prophecy
symfony/yaml
phpunit/PHPUnit
sebastian/comparator
sebastian/diff
sebastian/environment
sebastian/exporter
sebastian/global-state
sebastian/version

**Comment by Bittarman** [comment] 2015-06-16 10:39
Please could you expand on this somewhat? 
What command did you run? what composer version? 
On the face of it this sounds more like a composer / user error issue than a ZF one.

**Comment by svycka** [comment] 2015-06-16 11:41
I think this is duplicate of https://github.com/zendframework/zf2/issues/7574

**Comment by Maks3w** [comment] 2015-06-16 12:41
Duplicated #7574

**Closed by Maks3w** 2015-06-16 12:41 UTC
Labels: question
