### ISSUE TITLE
Cannot uncheck a checked checkbox

### ISSUE THREAD

**Issue by sparrowek** [zendframework/zf2#6559] opened 2014-08-12 08:09 UTC
I have a checkbox in a fieldset that I want to be checked by default

```php
        $this->add(array(
            'type' => 'checkbox',
            'name' => 'structured',
            'attributes' => array(
                'checked' => 'checked',
            ),
        ));
```

When a fieldset is bound to an object (e.g. from database) and the data for the fields is false or zero the checkbox in still checked.
I found that the `FormCheckbox` view helper does:

```php
$attributes            = $element->getAttributes();
// ...
if ($element->isChecked()) {
            $attributes['checked'] = 'checked';
}
```

So the checkbox can be checked but never unchecked. Is it by design?

**Comment by samsonasik** [comment] 2015-02-02 00:58
@sparrowek @Ocramius  this can be closed now...

**Comment by Ocramius** [comment] 2015-02-02 01:00
Closing as duplicate of zendframework/zf2-documentation#1363

**Closed by Ocramius** 2015-02-02 01:00 UTC
Labels: bug, duplicate, Form
