### ISSUE TITLE
TableGateway constructed with alias results in "array" in update()

### ISSUE THREAD

**Issue by Goram** [zendframework/zf2#7214] opened 2015-02-13 09:20 UTC
Hi,

I construct the TableGateway like this:

new TableGateway(
    array('t1' => 'web_user'),
    $adapter
)

in the update methods statement I´ll get:
  ["sql":protected] => string(60) "UPDATE Array SET username = :username WHERE globid = :where1"

Which results in a exception of my dbms:
SQLSTATE[42S02]: Base table or view not found: -206 [Informix][Informix ODBC Driver][Informix]The specified table (array) is not in the database. (SQLPrepare[-206] at /usr/local/src/modules/PDO_INFORMIX-1.3.1/informix_driver.c:131)

I temporarly solved it in Zend\Db\Sql\Update with:

        // create quoted table name to use in update processing
        if ($table instanceof TableIdentifier) {
            list($table, $schema) = $table->getTableAndSchema();
        } elseif (is_array($table)) {
            $table = current($table);
        }

**Comment by samsonasik** [comment] 2015-02-15 16:47
could you try develop branch ? many things was updated in zend\db for 2.4.0 ...

**Comment by mpalourdio** [comment] 2015-02-15 17:35
I don't use Zend\Db, but is Informix supported ?

**Comment by Goram** [comment] 2015-02-15 18:06
No, it is not, but alias in constructor is.

**Comment by Goram** [comment] 2015-02-17 08:55
@samsonasik 
Nop, doesn´t look like it:
https://github.com/zendframework/zf2/blob/develop/library/Zend/Db/Sql/AbstractSql.php#L299

The code was just moved

**Comment by adamlundrigan** [comment] 2015-11-06 21:14
Fixed in #7311

**Closed by adamlundrigan** 2015-11-06 21:14 UTC
Labels: Db

**Comment by adamlundrigan** [comment] 2015-11-06 21:16
Duplicate of #7430
