### ISSUE TITLE
when use form inputFilter getMessages return empty

### ISSUE THREAD

**Issue by wohugb** [zendframework/zf2#5164] opened 2013-09-24 06:36 UTC
If there have not riquried elments,when required elements are ok, $form->isValid() return false,but $form->getMessages() return empty!

**Comment by adamlundrigan** [comment] 2015-10-22 00:34
Duplicate of #4017.  See [this comment](https://github.com/zendframework/zf2/issues/4017#issuecomment-149965663) over there for rationale of why it's closed as not an issue. 

@Maks3w this can be closed

**Closed** 2015-10-22 06:09 UTC
Labels: InputFilter
