### ISSUE TITLE
how to pass a array(no numberic index) to a interface by POST?

### ISSUE THREAD

**Issue by zuoRambo** [zendframework/zf2#7496] opened 2015-05-07 06:09 UTC
talk is cheap,show you the code ~~
```
$paramPost = array('xxx','yyy','zzz');
$client = new Client('http://myhost/myinterface');
$client->setMethod('POST');
$client->setParameterPost(array(
        'image_name_array' => $paramPost,
));
$client->send();
$responseBody = $client->getResponse()->getBody();
```
when i print the request raw content,i find a question:
```
image_name_array%5B0%5D=xxx&image_name_array%5B1%5D=yyy&image_name_array%5B2%5D=zzz
```
the pretty format is:
```
image_name_array[0]=xxx&image_name_array[1]=yyy&image_name_array[2]=zzz
```
but the server expected the follow data: 'image_name_array[]=xxx&image_name_array[]=yyy&image_name_array[]=zzz' how to handle the question?

**Comment by zuoRambo** [comment] 2015-05-07 06:21
additional remarks: zf version 2.2.4 ,PHP 5.4.7 (cli) ,use Zend\Http\Client;

**Comment by Martin-P** [comment] 2015-05-07 07:52
> but the server expected the follow data: 'image_name_array[]=xxx&image_name_array[]=yyy&image_name_array[]=zzz'

You know there is no difference at all and both notations represent exactly the same array and both arrays have numeric indexes?

`image_name_array[]=xxx&image_name_array[]=yyy&image_name_array[]=zzz`:
```
image_name_array(
    0 => 'xxx',
    1 => 'yyy',
    2 => 'zzz',
)
```

`image_name_array[0]=xxx&image_name_array[1]=yyy&image_name_array[2]=zzz`:
```
image_name_array(
    0 => 'xxx',
    1 => 'yyy',
    2 => 'zzz',
)
```
Perhaps you are not telling the complete story, but at this moment it looks like basic array knowledge to me and not a ZF2 bug :wink:

**Comment by Bittarman** [comment] 2015-05-07 07:56
Closing as a support request and not a bug.

**Closed by Bittarman** 2015-05-07 07:56 UTC

**Comment by zuoRambo** [comment] 2015-05-07 08:12
nope, perhaps my description is't clear, i use Http\Client to post data to a server imitate form submit, but the request is not same as form action. the following js code segment working well:
```
var info=[];
info.push("xxx");
info.push("yyy");
info.push("zzz");
$.ajax({
        type: "POST",
        url: "myinterface",
        data:{ "image_name_array": info },
       success: function(result){
           console.log(result);        
       }
});
```
i think our zf2 should support this post way, though i know the programming way may be cumbersome but practical !

**Comment by Martin-P** [comment] 2015-05-07 09:17
> nope, perhaps my description is't clear, i use Http\Client to post data to a server imitate form submit, but the request is not same as form action.

The javascript code generates the same array again:
```
image_name_array(
    0 => 'xxx',
    1 => 'yyy',
    2 => 'zzz',
)
```
> i think our zf2 should support this post way, though i know the programming way may be cumbersome but practical !

Perhaps you can clarify the practical use for [] instead of [0]? If the use case is clear it might be easier to understand your point.

**Comment by zuoRambo** [comment] 2015-05-07 09:26
@Martin-P yes, it may be common in many cases or actual applications.

**Comment by Martin-P** [comment] 2015-05-07 09:33
> @Martin-P yes, it may be common in many cases or actual applications.

In that case it shouldn't be a problem to clarify your point. So please provide a use case, because it is still not clear why such a feature would be needed.
