### ISSUE TITLE
minimum PHP version bumped from 5.3 to 5.5

### ISSUE THREAD

**Issue by ecolinet** [zendframework/zf2#7635] opened 2015-10-09 09:07 UTC
From the overview page : "Zend Framework 2 is an open source framework for developing web applications and services using **PHP 5.3+**."

Today the minimum required version is set to **PHP 5.5**, I think that there's a **big problem** for companies (like mine) that relies on zf2 components.

Related to zendframework/zend-inputfilter#75

Thanks !

**Comment by localheinz** [comment] 2015-10-09 11:29
@ecolinet 

Well, actually the problem is that big companies like yours run unsupported PHP versions in production, isn't it? See http://php.net/supported-versions.php. 

However, even if you can't upgrade your production environment, you can still use older versions of ZF2, can't you?

Maybe this helps, too:

* https://github.com/philsturgeon/phpversions.info

**Comment by froschdesign** [comment] 2015-10-09 11:33
Or maybe this helps: [Version 2.4 has long term support](http://framework.zend.com/long-term-support/).

**Comment by ecolinet** [comment] 2015-10-09 13:39
Hi and thanks for your reply,

IMHO it depends on what you call "unsupported version".

The version we are using is perfectly supported (as much as ZF 2.4 LTS is)
by our Linux distribution vendor.

I'm afraid to read, again and again, that the only supported PHP versions
are the one supported by the PHP Group. That's totally WRONG. Many of us
are using distro packages that are always one, two or even three versions
late (5.4 in my case) but are perfectly supported and valid option to run
PHP on the said distro.

I still think that there is a problem in the ZF 2 Roadmap. ZF 2.5 should
have been ZF 3 since changing the runtime version is not a minor change,
it's a major change.




2015-10-09 13:34 GMT+02:00 Frank Brückner <notifications@github.com>:

**Comment by froschdesign** [comment] 2015-10-09 13:49
> Many of us are using distro packages that are always one, two or even three versions
late…

[Debian – for example – uses 5.6](https://packages.debian.org/stable/php/#php5)

Please see also the [comment from the project maintainer](https://github.com/zendframework/zend-inputfilter/issues/75#issuecomment-146834958).

**Comment by Maks3w** [comment] 2015-10-09 13:59
I'll close this because the main response is placed on https://github.com/zendframework/zend-inputfilter/issues/75

**Closed by Maks3w** 2015-10-09 13:59 UTC

**Comment by ecolinet** [comment] 2015-10-09 16:24
That's fine.
