### ISSUE TITLE
formCollection view helper doesn't translate value and label

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zf2#6611] opened 2014-08-28 23:38 UTC
when I used : 

```php
echo $this->formCollection($form);
```

with setting like this : 

```php
$serviceManager->get('ViewHelperManager')->get('formcollection')
                          ->setTranslatorTextDomain('myform');
```

It doesn't show the translated form value and label. possible it because of https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormCollection.php#L131-L148 that should be placed on https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormCollection.php#L114-L120 which elements are looped instead of calling one by one because : 

```php
$label = $element->getLabel();
```
is always empty.

**Comment by adamlundrigan** [comment] 2015-11-06 18:14
duplicate of #5826

**Closed by adamlundrigan** 2015-11-06 18:14 UTC
